config/routes.rb
Rails.application.routes.draw do

  resources :features

  namespace :admin do
    resources :dashboard
    resources :features
    resources :pages
    resources :settings
  end
  match '/admin' => 'admin/dashboard#index', :as => :admin

  match '/setup(/steps/:step_id)'    => 'setup#step', :as => :setup
  match '/setup/cartodb' => 'setup#cartodb', :as => :setup_cartodb
  match '/setup/features_table_data' => 'setup#features_table_data'
  match '/setup/create_features_table' => 'setup#create_features_table', :as => :create_table

  match "/auth/:provider/callback" => "sessions#create"

  get '/login' => 'sessions#create', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login_required' => 'sessions#new', :as => :login_required

  match ':controller(/:action(/:id))'

  resources :features
  root :to => "home#index"
end

app/views/admin/pages/_form.html.erb
<% content_for :javascripts do %>
  <script type="text/javascript" charset="utf-8">
    var texts = <%= t('.help').to_json.html_safe %>;
  </script>
  <%= javascript_include_tag 'jquery.min.js', 'jHtmlArea-0.7.0.min.js', 'admin/pages/new.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'admin/pages/form.css' %>
<% end %>

<%= form_for @page, :as => :page, :url => url, :html => { :method => method } do |form| %>
  <%= form.hidden_field :id %>
  <%= form.label :title, raw(t('.title') + content_tag(:strong, '*')), :class => :field_label %>
  <%= form.text_field :title, :class => :string %>

  <%= form.label :body, raw(t('.body') + content_tag(:strong, '*')), :class => :field_label %>
  <%= form.text_area :body, :class => :string %>

  <%= form.label :permalink, raw(t('.permalink') + content_tag(:strong, '*')), :class => 'field_label permalink' %>
  <%= form.text_field :permalink, :class => :string %>

  <span class="submit">
    <%= form.submit t(".#{action}.save"), :class => 'main_action' %>
    <%= form.check_box :visible, :class => :checkbox %>
    <%= form.label :visible, t('.visible'), :class => 'field_label visible' %>
  </span>
<% end %>

app/views/admin/pages/edit.html.erb
<div id="main_content">
  <div class="content_box table">
    <h1><%= t('.title') %></h1>
    <%= render 'form', :action => :update, :url => admin_page_path(@page.id.to_i), :method => :put %>
    <div class="side_bar">
      <a href="/admin/dashboard" class="back"><span></span><%= t('.back') %></a>
    </div>
  </div>
</div>

app/views/admin/pages/new.html.erb
  <% content_for :stylesheets do %>
    <%= stylesheet_link_tag 'admin/pages/new.css' %>
  <% end %>


  <div id="main_content">
    <div class="content_box table">
      <h1><%= t('.title') %></h1>
      <%= render 'form', :action => :create, :url => admin_pages_path, :method => :post %>
      <div class="side_bar">
        <a href="/admin/dashboard" class="back"><span></span><%= t('.back') %></a>
      </div>
    </div>
  </div>

app/views/admin/pages/show.html.erb
<% content_for :javascripts do %>
<%= javascript_include_tag 'jquery.min.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'admin/features/index.css' %>
<% end %>


<div class="content_box">
  <div class="left">
    <h1>Page <%=params[:id]%></h1>

    <label for="title" class="field_label">TITLE</label>
    <input type="text" id="title"/>

    <label for="body" class="field_label">BODY</label>
    <input type="text" id="body"/>

    <label for="permalink" class="field_label">PERMALINK</label>
    <input type="text" id="permalink"/>

    <a href="/admin/" class="main_action">Save changes</a>

  </div>

  <div class="right">
    <a href="/admin/" class="back">Back to dashboard</a>
    <div class="delete">
      <span>DELETE THIS PAGE</span>
      <p>Clicking the link below will permanently delete this page from the site</p>
      <a href="">Delete this page</a>
    </div>
  </div>
  <div class="clear"></div>
</div>

<div class="clear"></div>