config/routes.rb
Rails.application.routes.draw do

  resources :features

  namespace :admin do
    resources :dashboard
    resources :features
    resources :pages
    resources :settings
  end
  match '/admin' => 'admin/dashboard#index', :as => :admin

  match '/setup(/steps/:step_id)'    => 'setup#step', :as => :setup
  match '/setup/cartodb' => 'setup#cartodb', :as => :setup_cartodb
  match '/setup/features_table_data' => 'setup#features_table_data'
  match '/setup/create_features_table' => 'setup#create_features_table', :as => :create_table

  match "/auth/:provider/callback" => "sessions#create"

  get '/login' => 'sessions#create', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login_required' => 'sessions#new', :as => :login_required

  match ':controller(/:action(/:id))'

  resources :features
  root :to => "home#index"
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::AdminController

  def index
    @search           = OpenStruct.new params[:search]

    search_where      = generate_search_where(@search)

    @page             = (params[:page] || 1).to_i
    @features_columns = Feature.data_columns
    @features_count   = CartoDB::Connection.query("SELECT COUNT(cartodb_id) as features_count FROM #{Cartoset::Config['features_table']} #{search_where}").rows.first.features_count
    @features         = CartoDB::Connection.query(<<-SQL
      SELECT *
      FROM #{Cartoset::Config['features_table']}
      #{search_where}
      LIMIT 10
      OFFSET #{(@page - 1) * 10}
    SQL
    ).rows
    @pages            = (Cartoset::Config['pages'] || []).select{|p| p['id'].present? } || []
    @cartodb_host     = CartoDB::Settings['host']
    @table_id         = CartoDB::Connection.table(Cartoset::Config['features_table']).try(:id)
  end

  def generate_search_where(search_params)
    where = ''

    if search_params && search_params.q.present?
      where = []
      fields = Feature.non_common_fields.select{|f| f[:type] == 'string'}
      fields.each do |f|
        where << "#{f[:name]} ilike '%#{search_params.q.sanitize_sql!}%'"
      end
      where = "WHERE #{where.join(' OR ')}"
    end
    where
  end

end

app/views/admin/dashboard/index.html.erb
<% content_for :javascripts do %>
<%= javascript_include_tag 'jquery.min.js', 'jquery.scrollTo-1.4.2.js', 'admin/dashboard/index.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'admin/dashboard/index.css' %>
<% end %>

<div id="features_list" class="table">
  <span class="title"><%= t('.your_features') %></span>
  <div id="search">
    <%= form_for :search, :url => admin_path, :html => {:method => :get} do |f|%>
      <%= f.label 'q', t('.search_label') %>
      <%= f.text_field 'q' %>
      <%= f.submit t('.search') %>
    <% end %>
    <%= link_to content_tag(:span, t('.scroll_right')), '#', :id => 'scroll_right' %>
    <%= link_to content_tag(:span, t('.scroll_left')), '#', :id => 'scroll_left' %>
  </div>
  <div id="features_table">
    <table class="list">
      <tr class="header">
        <th><div class="id">id.</div></th>
        <% @features_columns.each do |column| %>
        <th><div class="<%= column[:type] %>"><%= column[:name] %></div></th>
        <% end %>
      </tr>
      <% @features.each do |feature| %>
        <tr class="item <%= cycle('odd', 'even') %>">
          <td class="cartodb_id"><%= link_to feature.cartodb_id, admin_feature_path(feature.cartodb_id) %></td>
          <% @features_columns.each do |column| %>
            <td class="<%= column.first %>"><%= feature.send(column[:name]).to_s.truncate(28) %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
  </div>
  <%= link_to t('.create_feature'), new_admin_feature_path, :id => 'create_feature', :class => 'main_action' %>
  <%= link_to t('.edit_in_cartodb'), "#{@cartodb_host}/tables/#{@table_id}", :id => 'edit_in_cartodb', :class => 'alternate_action' %>
  <%= raw paginate @features, @page, @features_count, params %>
</div>

<div id="pages_list" class="table">
  <div class="title"><%= t('.your_pages') %></div>
  <div class="pages_list_container">
    <ul>
      <% @pages.each do |page| %>
      <li>
        <div>
          <p><%= page['title'] %></p>
          <p class="link">
            <%= link_to t('.edit_this_page'), edit_admin_page_path(page['id'].to_i) %>
          </p>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="pages_footer">
    <%= link_to t('.create_new_page'), new_admin_page_path, :class => 'main_action' %>
  </div>
</div>

<% if false %>
<div id="settings_list" class="table">
  <span class="title">Settings</span>
  <div class="settings_list_container">
    <ul>
      <li class="odd" id="1">
        <div class="name">
          <p class="setting_name">services.google.tracking_id</p>
          <p class="setting_description">Integration ID with Google Analytics</p>
        </div>
        <div class="setting_value"><a href="">UA-1234567-1</a></div>
        <div class="edit_value">
          <input type="text" value="UA-1234567-1"/>
          <input type="hidden" value="UA-1234567-1"/>
          <a href="" class="action_input">Save</a>
          <span class="cancel_value">or <a href="">cancel</a></span>
        </div>
      </li>
      <li class="even" id="2">
        <div class="name">
          <p class="setting_name">services.google.tracking_id</p>
          <p class="setting_description">Integration ID with Google Analytics</p>
        </div>
        <div class="setting_value"><a href="">UA-1234567-2</a></div>
        <div class="edit_value">
          <input type="text" value="UA-1234567-2"/>
          <input type="hidden" value="UA-1234567-2"/>
          <a href="" class="action_input">Save</a>
          <span class="cancel_value">or <a href="">cancel</a></span>
        </div>
      </li>
      <li class="odd last" id="3">
        <div class="name">
          <p class="setting_name">services.google.tracking_id</p>
          <p class="setting_description">Integration ID with Google Analytics</p>
        </div>
        <div class="setting_value"><a href="">UA-1234567-3</a></div>
        <div class="edit_value">
          <input type="text" value="UA-1234567-3"/>
          <input type="hidden" value="UA-1234567-3"/>
          <a href="" class="action_input">Save</a>
          <span class="cancel_value">or <a href="">cancel</a></span>
        </div>
      </li>
    </ul>
  </div>
  <div class="settings_footer"></div>
</div>
<% end %>