config/routes.rb
Rails.application.routes.draw do

  resources :features

  namespace :admin do
    resources :dashboard
    resources :features
    resources :pages
    resources :settings
  end
  match '/admin' => 'admin/dashboard#index', :as => :admin

  match '/setup(/steps/:step_id)'    => 'setup#step', :as => :setup
  match '/setup/cartodb' => 'setup#cartodb', :as => :setup_cartodb
  match '/setup/features_table_data' => 'setup#features_table_data'
  match '/setup/create_features_table' => 'setup#create_features_table', :as => :create_table

  match "/auth/:provider/callback" => "sessions#create"

  get '/login' => 'sessions#create', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login_required' => 'sessions#new', :as => :login_required

  match ':controller(/:action(/:id))'

  resources :features
  root :to => "home#index"
end

app/controllers/setup_controller.rb
class SetupController < ApplicationController
  include FeatureGetterHelper

  layout 'setup'

  before_filter :redirect_to_root_if_invalid_env
  skip_before_filter :show_setup_wizard_if_uninstalled

  def step
    step_id = params[:step_id] || 0

    case step_id
    when "1"
      @settings = OpenStruct.new Cartoset::Config.settings
    when "2"
      Cartoset::Config.set_cartodb_credentials current_user
      @settings = OpenStruct.new Cartoset::Config.settings
    when "3"
      Cartoset::Config.update params[:settings]

      result = CartoDB::Connection.tables || []
      @tables = result.tables
    when "4"
      @table = CartoDB::Connection.table params[:features_table]
      Cartoset::Config.update :features_table => @table.name
    end

    render "step#{step_id}"
  end

  def cartodb
      Cartoset::Config.update params[:settings]

      Cartoset::Config.setup_cartodb

      session[:return_to] = setup_path(:step_id => 2)

      redirect_to '/auth/cartodb' and return
  end

  def features_table_data
    table_name = params[:table_name]
    if table_name
      @table  = CartoDB::Connection.table table_name
      records = CartoDB::Connection.records table_name, {}
      @rows = records.rows if records
    end
    render :layout => false
  end

  def create_features_table
    table = {}

    if params[:qqfile] && request.body.present?
      table = FeaturesDataImporter.start request.body
    end

    render :json => table.to_json
  end

  def redirect_to_root_if_invalid_env
    unless Rails.env.development? || Rails.env.test? || logged_in?
      if application_installed? && !logged_in?
        session[:return_to] = setup_path
        redirect_to login_required_path
      else
        redirect_to root_path
      end
    end
  end
  private :redirect_to_root_if_invalid_env
end

app/views/setup/_step_indicator.erb
<ol class="step_indicator">
  <li class="<%= "selected" if step==1%>">
    <span class="step_number">1</span>
    <span class="step_description"><%= t('.step_1') %></span>
  </li>
  <li class="<%= "selected" if step==2%>">
    <span class="step_number">2</span>
    <span class="step_description"><%= t('.step_2') %></span>
  </li>
  <li class="<%= "selected" if step==3%>">
    <span class="step_number">3</span>
    <span class="step_description"><%= t('.step_3') %></span>
  </li>
</ol>

app/views/setup/features_table_data.html.erb
<table class="data">
  <tr>
    <% @table.schema.first(3).each do |column| %>
    <th class="<%= column.last %>"><%= column.first %></th>
    <% end %>
  </tr>
  <% if @rows.present? %>
    <% first_row = @rows.shift %>
    <tr>
      <% first_row.values.first(3).each do |cell| %>
        <td class="first"><%= truncate(cell.to_s, :length => 35) %></td>
      <% end %>
    </tr>
    <% @rows.each do |row| %>
      <tr class="item <%= cycle('odd', 'even') %>">
        <% row.values.first(3).each do |cell| %>
          <td><%= truncate(cell.to_s, :length => 35) %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
</table>

app/views/setup/step0.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'setup/index', 'setup/step0' %>
<% end %>

<div class="small_content_box">
  <h1 class="lowered"><%= t('.congrats') %></h1>
  <p class="success_message"><%= t('.success') %></p>
  <%= link_to t('.start'), setup_path(:step_id => 1), :class => 'main_action' %>
</div>

app/views/setup/step1.html.erb
<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'setup/index.css', 'setup/step1.css' %>
<% end %>

<% content_for :javascripts do %>
  <%= javascript_include_tag 'jquery.min.js', 'spin.js', 'setup/step1.js' %>
<% end %>

<%= render 'step_indicator', :step => 1 %>

<div class="small_content_box">
  <h1><%= t('.title') %></h1>
  <p><%= t('.description') %></p>
  <br />
  <p><%= t('.continue') %></p>
  <br />

  <%= form_for @settings, :as => :settings, :url => setup_cartodb_path, :html => { :method => :get } do |form| %>
    <div class="field">
      <%= form.label 'cartodb_host', t('.oauth_host'), :class => 'host' %>
      <%= form.text_field 'cartodb_host' %>
    </div>
    <div class="field">
      <%= form.label 'cartodb_oauth_key', t('.oauth_key'), :class => 'oauth_key' %>
      <%= form.text_field 'cartodb_oauth_key' %>
    </div>
    <div class="field">
      <%= form.label 'cartodb_oauth_secret', t('.oauth_secret'), :class => 'oauth_secret' %>
      <%= form.text_field 'cartodb_oauth_secret' %>
    </div>
    <div class="submit">
      <%= form.submit t('.connect_with_cartodb'), :class => 'main_action' %>
    </div>
  <% end %>

</div>

app/views/setup/step2.html.erb
<% content_for :javascripts do %>
<%= javascript_include_tag 'jquery.min.js', 'setup/step2.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'setup/index.css', 'setup/step2.css' %>
<% end %>

<%= render 'step_indicator', :step => 2 %>

<div class="small_content_box">
  <h1><%= t('.title') %></h1>
  <p><%= t('.description') %></p>
  <%= form_for @settings, :as => :settings, :url => setup_path(:step_id => 3), :html => { :method => :get } do |form| %>
    <%= form.label 'app_name', t('.app_name') %>
    <%= form.text_field 'app_name' %>
    <%= form.submit t('.next_step'), :class => 'main_action' %>
  <% end %>
</div>

app/views/setup/step3.html.erb
<% content_for :javascripts do %>
<%= javascript_include_tag 'jquery.min.js', 'fileuploader.js', 'spin.js', 'jquery.jscrollpane.min.js', 'jquery.mousewheel.js', 'setup/step3.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'setup/index.css', 'setup/step3.css', 'jscrollpane.css' %>
<% end %>

<%= render 'step_indicator', :step => 3 %>
<%= form_tag setup_path(:step_id => 4) do %>
  <div class="small_content_box">
    <h1><%= t('.title') %></h1>
    <p><%= t('.description') %></p>

    <div id="select_table" class="shadowed">
      <a href="#" class="selector">Select table</a> <span id="new_table"><%= raw t('.or', :link => link_to(t('.create_a_new_one'), '#')) %></span>
      <ul id="tables_combo" class="selector_values scroll_pane">
        <% @tables.each do |table| %>
        <li><a href="#"><%= table.name %></a></li>
        <% end %>
      </ul>
      <%= select_tag 'features_table', options_for_select(@tables.map{|t| [t.name, t.name]}), {:include_blank => true} %>
      <div id="table_data"></div>
    </div>

    <div id="create_table" class="shadowed">
      <div id="file-uploader">
        select
        <noscript>
          <%= form_tag create_table_path do %>
            <%= label_tag 'data_file' %>
            <%= file_field_tag 'data_file' %>
            <%= submit_tag 'Submit' %>
          <% end %>
        </noscript>
      </div>
      <span class="select_file message">Select a data file (CSV,XLS) from your computer</span>
      <span class="processing message">Processing your file...</span>
    </div>
    <div id="spinner"></div>
    <%= submit_tag t('.use_this_table'), :id => 'use_this_table', :class => 'main_action right', :disabled => true %>
  </div>
<% end %>

app/views/setup/step4.html.erb
<% content_for :javascripts do %>
<%= javascript_include_tag 'jquery.min.js', 'admin/setup/index.js' %>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'setup/index.css' %>
  <%= stylesheet_link_tag 'setup/step4.css' %>
<% end %>

<div class="small_content_box">
  <h1><%= t('.title') %></h1>
  <p><%= t('.description') %></p>

  <div class="shadowed">
    <div class="suggestion" id="manage_data">
      <h2><%= t('.manage_data.title') %></h2>
      <p><%= t('.manage_data.description') %></p>
      <%= link_to t('.manage_data.link'), "#{CartoDB::Settings['host']}/tables/#{@table.id}" %>
    </div>
    <div class="suggestion" id="manage_site">
      <h2><%= t('.manage_site.title') %></h2>
      <p><%= t('.manage_site.description') %></p>
      <%= link_to t('.manage_site.link'), admin_path %>
    </div>
    <div class="suggestion last" id="public_site">
      <h2><%= t('.public_site.title') %></h2>
      <p><%= t('.public_site.description') %></p>
      <%= link_to t('.public_site.link'), root_path %>
    </div>
  </div>
</div>