config/routes.rb
Rails.application.routes.draw do

  resources :features

  namespace :admin do
    resources :dashboard
    resources :features
    resources :pages
    resources :settings
  end
  match '/admin' => 'admin/dashboard#index', :as => :admin

  match '/setup(/steps/:step_id)'    => 'setup#step', :as => :setup
  match '/setup/cartodb' => 'setup#cartodb', :as => :setup_cartodb
  match '/setup/features_table_data' => 'setup#features_table_data'
  match '/setup/create_features_table' => 'setup#create_features_table', :as => :create_table

  match "/auth/:provider/callback" => "sessions#create"

  get '/login' => 'sessions#create', :as => :login
  get '/logout' => 'sessions#destroy', :as => :logout
  get '/login_required' => 'sessions#new', :as => :login_required

  match ':controller(/:action(/:id))'

  resources :features
  root :to => "home#index"
end

app/views/admin/shared/_footer.html.erb
<footer>
  <div id="footer_content">POWERED BY <a href="">CARTOSET</a></div>
</footer>

app/views/admin/shared/_header.html.erb
<header>
  <div id="header_content">
    <h1 id="logo"><%= link_to 'CartoSet', admin_path %></h1>
    <nav>
      <ul>
        <li><%= link_to t('.features'), admin_path(:anchor => 'features'), :id => 'features_menu_link' %></li>
        <li><%= link_to t('.pages'), admin_path(:anchor => 'pages'), :id => 'pages_menu_link' %></li>
        <% if false %><li><%= link_to t('.settings'), '#' , :id => 'settings_menu_link'%></li><% end %>
        <li><%= link_to t('.close_session'), logout_path, :class => 'close_session' %></li>
      </ul>
    </nav>
  </div>
</header>